{
 "title": "1 SLS主机监控 v2020.08.08",
 "description": "SLS主机监控，主要显示单主机指标",
 "tags": [
  "Logtail",
  "SLS",
  "Prometheus"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "Host",
    "label": "Host",
    "query": "label_values(system_boot_time, hostname)"
   },
   {
    "name": "IP",
    "label": "IP",
    "query": "label_values(system_boot_time, ip)"
   }
  ]
 },
 "panels": [
  {
   "title": "启动天数",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(time() - max(system_boot_time{hostname=~\"$Host\", ip=~\"$IP\"}))/86400",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "CPU核心数",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(cpu_count{hostname=~\"$Host\", ip=~\"$IP\"})",
     "legendFormat": "count"
    }
   ]
  },
  {
   "title": "内存总量",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(mem_total{hostname=~\"$Host\", ip=~\"$IP\"}) / 1024.0/1024/1024",
     "legendFormat": "count"
    }
   ]
  },
  {
   "title": "磁盘Util",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 4, "x": 9, "y": 0 },
   "targets": [
    {
     "expr": "avg(disk_util{hostname=~\"$Host\", ip=~\"$IP\"}) by (disk) / 100",
     "legendFormat": "{{disk}}"
    }
   ]
  },
  {
   "title": "各磁盘空间使用率",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 11, "x": 13, "y": 0 },
   "targets": [
    {
     "expr": "avg(disk_space_usage{hostname=~\"$Host\", ip=~\"$IP\"}) by (path)",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "CPU使用率",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 13, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "avg(cpu_util{hostname=~\"$Host\", ip=~\"$IP\"})",
     "legendFormat": "util"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 5 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(cpu_sys_util{hostname=~\"$Host\", ip=~\"$IP\"})",
     "legendFormat": "System"
    },
    {
     "expr": "avg(cpu_user_util{hostname=~\"$Host\", ip=~\"$IP\"})",
     "legendFormat": "User"
    },
    {
     "expr": "avg(cpu_wait_util{hostname=~\"$Host\", ip=~\"$IP\"})",
     "legendFormat": "IOWait"
    }
   ]
  },
  {
   "title": "内存",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 5, "w": 7, "x": 6, "y": 5 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(mem_available{hostname=~\"$Host\", ip=~\"$IP\"})",
     "legendFormat": "available"
    },
    {
     "expr": "avg(mem_used{hostname=~\"$Host\", ip=~\"$IP\"})",
     "legendFormat": "used"
    }
   ]
  },
  {
   "title": "Inode使用率",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 11, "x": 13, "y": 5 },
   "targets": [
    {
     "expr": "avg(disk_inode_usage{hostname=~\"$Host\", ip=~\"$IP\"})  by (path)",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "CPU使用率",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg(cpu_util{hostname=~\"$Host\", ip=~\"$IP\"})",
     "legendFormat": "cpu_util"
    },
    {
     "expr": "avg(cpu_sys_util{hostname=~\"$Host\", ip=~\"$IP\"})",
     "legendFormat": "cpu_sys_util"
    },
    {
     "expr": "avg(cpu_user_util{hostname=~\"$Host\", ip=~\"$IP\"})",
     "legendFormat": "cpu_user_util"
    },
    {
     "expr": "avg(cpu_wait_util{hostname=~\"$Host\", ip=~\"$IP\"})",
     "legendFormat": "cpu_wait_util"
    }
   ]
  },
  {
   "title": "Load",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(system_load1{hostname=~\"$Host\", ip=~\"$IP\"})",
     "legendFormat": "load_1"
    },
    {
     "expr": "avg(system_load5{hostname=~\"$Host\", ip=~\"$IP\"})",
     "legendFormat": "load_5"
    },
    {
     "expr": "avg(system_load15{hostname=~\"$Host\", ip=~\"$IP\"})",
     "legendFormat": "load_15"
    }
   ]
  },
  {
   "title": "磁盘Util",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg(disk_util{hostname=~\"$Host\", ip=~\"$IP\"}) by (disk)",
     "legendFormat": "{{disk}}"
    }
   ]
  },
  {
   "title": "根目录磁盘使用率",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "disk_space_usage{path=\"/\",hostname=~\"$Host\", ip=~\"$IP\"}",
     "legendFormat": "util_{{ip}}"
    }
   ]
  },
  {
   "title": "磁盘读写速率",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 18 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "avg(disk_rbps{disk=\"total\", hostname=~\"$Host\", ip=~\"$IP\"}) by (disk)",
     "legendFormat": "{{disk}}_read(Bps)"
    },
    {
     "expr": "avg(disk_wbps{disk=\"total\",hostname=~\"$Host\", ip=~\"$IP\"}) by (disk)",
     "legendFormat": "{{disk}}_write(Bps)"
    }
   ]
  },
  {
   "title": "磁盘读写延迟",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(disk_rlatency{disk=\"total\", hostname=~\"$Host\", ip=~\"$IP\"})",
     "legendFormat": "read(ms)"
    },
    {
     "expr": "avg(disk_wlatency{disk=\"total\", hostname=~\"$Host\", ip=~\"$IP\"})",
     "legendFormat": "write(ms)"
    }
   ]
  },
  {
   "title": "各磁盘空间使用率",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg(disk_space_usage{hostname=~\"$Host\", ip=~\"$IP\"}) by (path)",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "各磁盘读写速率",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 25 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "avg(disk_rbps{disk!=\"total\", hostname=~\"$Host\", ip=~\"$IP\"}) by (disk)",
     "legendFormat": "{{disk}}_read(Bps)"
    },
    {
     "expr": "avg(disk_wbps{disk!=\"total\",hostname=~\"$Host\", ip=~\"$IP\"}) by (disk)",
     "legendFormat": "{{disk}}_write(Bps)"
    }
   ]
  },
  {
   "title": "各磁盘读写延迟",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(disk_rlatency{disk!=\"total\", hostname=~\"$Host\", ip=~\"$IP\"}) by (disk)",
     "legendFormat": "{{disk}}_read(ms)"
    },
    {
     "expr": "avg(disk_wlatency{disk!=\"total\", hostname=~\"$Host\", ip=~\"$IP\"})by (disk)",
     "legendFormat": "{{disk}}_write(ms)"
    }
   ]
  },
  {
   "title": "网络IO",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "net_in{interface=\"total\",hostname=~\"$Host\", ip=~\"$IP\"}",
     "legendFormat": "in(Bps)"
    },
    {
     "expr": "net_out{interface=\"total\",hostname=~\"$Host\", ip=~\"$IP\"}",
     "legendFormat": "out(Bps)"
    }
   ]
  },
  {
   "title": "各网卡IO",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "net_in{interface!=\"total\",hostname=~\"$Host\", ip=~\"$IP\"}",
     "legendFormat": "{{interface}}_in(Bps)"
    },
    {
     "expr": "net_out{interface!=\"total\",hostname=~\"$Host\", ip=~\"$IP\"}",
     "legendFormat": "{{interface}}_out(Bps)"
    }
   ]
  },
  {
   "title": "TCP连接数",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(protocol_tcp_established{hostname=~\"$Host\", ip=~\"$IP\"})",
     "legendFormat": "tcp_established"
    }
   ]
  },
  {
   "title": "TCP重传率",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg(protocol_tcp_retran_util{hostname=~\"$Host\", ip=~\"$IP\"})",
     "legendFormat": "retran"
    }
   ]
  }
 ]
}